parameters:
    twig.extension.feather.class: Feather\Bundle\CoreBundle\Twig\FeatherExtension
    feather.form.torrent_add.class: Feather\Bundle\CoreBundle\Form\TorrentFileType

services:
    feather.twig.feather_extension:
        class: %twig.extension.feather.class%
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: twig.extension }
    app.form.torrent_add:
        class: %feather.form.torrent_add.class%
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: form.type, alias: torrent_add }
